const description = `<p>These are a series of texture assets I have made in the program <strong><a rel='noopener noreferrer' target='_blank' href="https://quixel.com/mixer">Quixel Mixer</a></strong>. Mixer is an alternative to programs like substance painter that has seen a quick and steady rise in terms of its use in triple A movie and game projects. I have always appreciated the insane detail you can find in something as simple as a broken brick wall in modern video games to the point that I had to attempt something similar myself.</p>

<p>This was a personal project that really showed me that even as a single person with limited experience in 3D I could create something photoreal. It also gave me a newfound respect for the texture and environment artists that are often forgotten about as the time you can spend on a floor texture compared to how long someone will actually view it is incomparable. This project also taught me one last lesson in terms of the scope of triple A titles. While I might be able to make textures, 3D models, concept art and some other assets, there are still so many things I am completely unable to do. When working on personal projects now I have very much limited my scope to make them at least realistically doable instead of picturing a whole moden game coming out of my computer alone.</p>

<p>For anyone interested in the more technical aspect of how these textures are made to look photoreal, I will explain here in a bit more detail. Each individual texture has two corresponding 3D and 2D photos, they are all made with a variety of maps including, Albedo, Diffuse, Specular, Gloss, Roughness, Normal, Displacement, AO and Metalness. These are meant to exponentially increase the texture’s fidelity by providing the most realistic form of lighting, shading and texture information. The final textures are also made with a variety of photorealistic <strong><a rel='noopener noreferrer' target='_blank' href="https://quixel.com/megascans">Megascans </a></strong> from Quixel’s library giving them a photoreal starting point that you then take further.</p>

<hr/>

<p><strong>Links to Programs Used:</strong></p>

<ul><li><a rel='noopener noreferrer' target='_blank' href="https://quixel.com/mixer">Quixel Mixer</a></li><li><a rel='noopener noreferrer' target='_blank' href="https://quixel.com/bridge">Quixel Bridge</a></li><li><a rel='noopener noreferrer' target='_blank' href="https://quixel.com/megascans">Quixel Megascans</a></li><li><a rel='noopener noreferrer' target='_blank' href="https://www.adobe.com/products/photoshop.html">Adobe Photoshop</a></li></ul>`
export default description
