const description = `<h2>About Me</h2>

<p>Hi, my name is Dante Livingston. I am currently a third year Digital Media Art student at San Jose State University. I grew up in San Diego in Southern California and from a very early period in my life, my parents took me hiking and camping. This manifested itself into my love for the outdoors in later years and now I enjoy bringing nature and environmental themes into my work. I consume a huge variety of media including books, movies, foreign media and video games which has given me a wide view of different artforms since childhood. I have always been a media sponge and hope to work in one of the industries related to media production for my career.</p>

<h2>Artist&#39;s Statement</h2>

<p>I work primarily within the digital space, however I will still never forget what environment my physical body lives in. So much art is made digitally as a way to move towards ease of production, ease of access, freedom from traditional constraints and to put less of a strain on the environment. However, often the physical world is forgotten by digital artists as they primarily focus on the medium they intend their work to be viewed in. We see more and more disparity and tension between traditional and digital artwork, when really we should be unifying the two under one banner. I work extensively in both traditional and digital mediums and have been trying to merge as many skills between the two as I can. Though digital art can be very different from its traditional counterpart, many of the key concepts and fundamentals are the same. Understanding perspective, composition, color theory, and much more are all deeply rooted in art as a whole, not just traditional painting. By being able to focus on the fundamentals and utilize them to their fullest extent in digital work, I have been able to create more interesting and creative projects than I would have if I just pushed forward using technology as a crutch. This also has given me a significant feeling of fulfillment as I am constantly pushing myself forward and building off of what I already know.</p>

<p>As an individual, I have always been an environmentalist and have been able to include related themes within my artwork. Bringing conservation and anti pollution messages into my digital work has been more of a struggle than with traditional projects, however it is still very doable, albeit different. Within my digital art, I have found a way to express information as a more interactive experience than I had before with my traditional projects. This allows me to connect with the viewer on a more intimate level and give the audience a new level of immersion to be engulfed into. Moreso, it has freed me from many, mostly physical, constraints previously holding me back.</p>

<p>By utilizing the myriad of resources produced by those more talented than myself, I have been able to truly expand my horizons. New technologies and tools are constantly being produced, and through my use of them I have been able to push myself further to create my best work possible. Through the digital media medium, as the technology surrounding my art improves and I improve by myself, my art has been able to significantly step up.</p>`
export default description
